-- Drop check constraint if exists (PostgreSQL automatically drops check constraints when altering column type using cast, but here we just have varchar)
-- Actually, if we created it previously without check constraint, we are fine.
-- If there was a check constraint generated by hibernate hbm2ddl, we might need to drop it, but flyway assumes we manage schema manually.

-- 1. Add new columns
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancel_reason VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS admin_comment TEXT;

-- 2. Migrate old statuses
-- PENDING -> PENDING_PAYMENT
UPDATE orders SET status = 'PENDING_PAYMENT' WHERE status = 'PENDING';

-- Other status migrations if necessary. For now, assuming PENDING was the main change.
